name: earthcal
version: '0.9.2'
summary: Earthcal
description: |
  Sync your moments with Earth's cycles.
base: core20
confinement: strict
grade: stable

apps:
  earthcal:
    command: earthcal
    extensions: [gnome-3-38]
    plugs:
      - browser-support
      - desktop
      - home
      - network
      - network-bind
      - x11

    environment:
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  earthcal:
    plugin: dump
    source: earthcal-linux-x64/
    build-snaps:
    - node/14/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4


