
#npx electron-builder --linux snap
# sudo snap remove earthcal
# sudo snap install --dangerous dist/earthcal_0.7.9_amd64.snap
# earthcal



# snapcraft login
# snapcraft upload dist/earthcal_0.7.9_amd64.snap
# snapcraft release earthcal edge
# sudo snap remove earthcal
# sudo snap install earthcal --edge
# OR  sudo snap refresh earthcal --edge


name: earthcal
version: '0.7.9'
summary: Earthcal | EarthCycles Calendar
description: |
  Sync your moments with Earthen cycles
base: core22
confinement: strict
grade: stable

parts:
  earthcal:
    plugin: nil
    source: .
    build-packages:
      - curl
    override-build: |
      # Install Node.js v18
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      
      # Force install Node.js v18 with overwrite option to handle file conflicts
      apt-get install -y nodejs --allow-downgrades --allow-remove-essential --allow-change-held-packages
      
      # Verify Node.js version
      node -v
      
      npm install
      npm run package
      
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      # Copy the output from linux-unpacked
      cp -r dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/bin/
    stage-packages:
      - libx11-6
      - libxcomposite1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxrandr2
      - libasound2
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libcairo2
      - libcups2
      - libgbm1
      - libgtk-3-0
      - libnspr4
      - libnss3
      - libpango-1.0-0
      - libxcb1
      - libxkbcommon0

apps:
  earthcal:
    command: desktop-launch $SNAP/bin/Earthcal
    plugs:
      - browser-support
      - desktop
      - home
      - network
      - network-bind
      - x11
