
name: earthcal
version: '0.9.0'
summary: EarthCal  | EarthCycles Calendar
description: |
  Sync your moments with Earthen cycles.
base: core22
confinement: strict
grade: stable

apps:
  earthcal:
    command: earthcal
#    extensions: [gnome-3-38]
    plugs:
      - browser-support
      - desktop
      - home
      - network
      - network-bind
      - x11

    environment:
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  earthcal:
    plugin: dump
    source: earthcal-linux-x64/
    build-snaps:
    - node/14/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4

# // snapcraft
# // sudo snap install --dangerous ./earthcal_0.4.0_amd64.snap
# // snapcraft login
# // snapcraft push earthcal_0.4.15_amd64.snap
# //sudo snap refresh earthcal