name: earthcal
version: '0.9.7'
summary: Earthcal
description: |
  Sync your moments with Earth's cycles.

base: core22
confinement: strict
grade: stable

apps:
  earthcal:
    command: earthcal
    extensions: [gnome]
    plugs:
      - browser-support
      - desktop
      - desktop-legacy
      - home
      - network
      - network-bind
      - x11
      - gsettings
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      ELECTRON_DISABLE_SANDBOX: 1

parts:
  earthcal:
    plugin: dump
    source: earthcal-linux-x64/
    build-snaps:
      - node/14/stable
    build-packages:
      - unzip
    stage-packages:
      - libnss3
      - libnspr4
      - libgtk-3-0
      - libcanberra-gtk3-module

