name: earthcal
title: EarthCal | EarthCycles Calendar
version: '1.1.0'
summary: Earthcal
description: |
  Sync your moments with Earth's cycles.

base: core22
confinement: strict
grade: stable

# Recommended metadata for the store & linter
license: CC-BY-NC-SA-4.0
contact: admin@earthcal.app
website: https://earthcal.app
source-code: https://github.com/russs95/earthcal
issues: https://github.com/russs95/earthcal/issues
donation: https://earthen.io

apps:
  earthcal:
    command: earthcal
    extensions: [gnome]
    plugs:
      - browser-support
      - desktop
      - desktop-legacy
      - home
      - network
      - network-bind
      - x11
      - gsettings
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      ELECTRON_DISABLE_SANDBOX: 1
      GTK_MODULES: ""   # prevent trying to load canberra/atk GTK modules


parts:
  earthcal:
    plugin: dump
    source: earthcal-linux-x64/
    build-snaps:
      - node/14/stable
    build-packages:
      - unzip
    stage-packages:
      - libnss3
      - libnspr4
      - libgtk-3-0
      - libcanberra-gtk3-module
