name: earthcal
version: '0.9.5'
summary: Earthcal
description: |
  Sync your moments with Earth's cycles.
base: core22
confinement: strict
grade: stable

apps:
  earthcal:
    command: earthcal
    extensions: [gnome]
    plugs:
      - browser-support
      - desktop
      - desktop-legacy
      - home
      - network
      - network-bind
      - x11
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      ELECTRON_DISABLE_SANDBOX: 1
      GTK_MODULES: "unset"

parts:
  earthcal:
    plugin: dump
    source: earthcal-linux-x64/
    build-snaps:
      - node/14/stable
    build-packages:
      - unzip
    stage-packages:
      - libnss3
      - libnspr4
    organize:
      snap/gui/earthcal.desktop: usr/share/applications/earthcal.desktop
      snap/gui/earthcal.png: usr/share/icons/hicolor/512x512/apps/earthcal.png
