name: earthcal
title: EarthCAL | EarthCycles Calendar
version: '1.3.9'
summary: EarthCal
description: |
  Sync your moments with Earth's cycles.

base: core24
confinement: strict
grade: stable
icon: snap/gui/earthcal.png
# Recommended metadata for the store & linter
license: CC-BY-NC-SA-4.0
contact: admin@earthcal.app
website: https://earthcal.app
source-code: https://github.com/russs95/earthcal
issues: https://github.com/russs95/earthcal/issues
donation: https://earthen.io

apps:
  earthcal:
    command: earthcal --no-sandbox
    desktop: meta/gui/earthcal.desktop
    extensions: [gnome]
    plugs:
      - browser-support
      - desktop
      - home
      - network
      - x11
      - wayland
      - gsettings
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      GTK_MODULES: ""


lint:
  ignore:
    - library


parts:
  earthcal:
    plugin: dump
    source: earthcal-linux-x64/
    stage-packages:
      - libnss3
      - libnspr4
    prime:
      - .
      - -LICENSES.chromium.html
